import type { Room } from "./types";

export const ROOMS: Room[] = [
  {
    id: "sub-2310",
    name: "SUB Dining Area 2310",
    shortName: "SUB 2310",
    buildingCode: "SUB",
    building: "Student Union Building",
    floor: 2,
    roomNumber: "2310",
    latitude: 49.27942,
    longitude: -122.92272,
    areaM2: 278.7,
    capacity: 150,
    hours: "9am–10pm",
    outlets: false,
    verification: "listed",
  },
  {
    id: "sub-2330",
    name: "SUB Public Lounge 2330",
    shortName: "SUB 2330",
    buildingCode: "SUB",
    building: "Student Union Building",
    floor: 2,
    roomNumber: "2330",
    latitude: 49.27942,
    longitude: -122.92232,
    areaM2: 92.9,
    capacity: 50,
    hours: "9am–10pm",
    outlets: false,
    verification: "listed",
  },
  {
    id: "sub-4210",
    name: "SUB Public Lounge 4210",
    shortName: "SUB 4210",
    buildingCode: "SUB",
    building: "Student Union Building",
    floor: 4,
    roomNumber: "4210",
    latitude: 49.27958,
    longitude: -122.92252,
    areaM2: 92.9,
    capacity: 50,
    hours: "9am–10pm",
    outlets: true,
    verification: "listed",
  },
  {
    id: "sub-4215",
    name: "SUB Public Lounge 4215",
    shortName: "SUB 4215",
    buildingCode: "SUB",
    building: "Student Union Building",
    floor: 4,
    roomNumber: "4215",
    latitude: 49.27958,
    longitude: -122.92225,
    areaM2: 44.6,
    capacity: 24,
    hours: "9am–10pm",
    outlets: true,
    verification: "listed",
  },
  {
    id: "sub-4100",
    name: "SUB Public Lounge 4100",
    shortName: "SUB 4100",
    buildingCode: "SUB",
    building: "Student Union Building",
    floor: 4,
    roomNumber: "4100",
    latitude: 49.27958,
    longitude: -122.92279,
    areaM2: 18.6,
    capacity: 10,
    hours: "9am–10pm",
    outlets: true,
    verification: "listed",
  },
  {
    id: "sub-4300",
    name: "SUB Public Lounge 4300",
    shortName: "SUB 4300",
    buildingCode: "SUB",
    building: "Student Union Building",
    floor: 4,
    roomNumber: "4300",
    latitude: 49.27974,
    longitude: -122.92268,
    areaM2: 37.2,
    capacity: 20,
    hours: "9am–10pm",
    outlets: true,
    verification: "listed",
  },
  {
    id: "sub-5300",
    name: "SUB Public Lounge 5300",
    shortName: "SUB 5300",
    buildingCode: "SUB",
    building: "Student Union Building",
    floor: 5,
    roomNumber: "5300",
    latitude: 49.27974,
    longitude: -122.92236,
    areaM2: 92.9,
    capacity: 50,
    hours: "9am–10pm",
    outlets: true,
    verification: "listed",
  },
  {
    id: "aq-303",
    name: "AQ Public Lounge 303",
    shortName: "AQ 303",
    buildingCode: "AQ",
    building: "Academic Quadrangle",
    floor: 3,
    roomNumber: "303",
    latitude: 49.2782,
    longitude: -122.91972,
    areaM2: 130.1,
    capacity: 70,
    hours: "9am–10pm",
    outlets: true,
    verification: "listed",
  },
  {
    id: "wmc-1500",
    name: "WMC Public Study Area 1500",
    shortName: "WMC 1500",
    buildingCode: "WMC",
    building: "West Mall Centre",
    floor: 1,
    roomNumber: "1500",
    latitude: 49.27847,
    longitude: -122.92355,
    areaM2: 92.9,
    capacity: 50,
    hours: "All day",
    outlets: true,
    verification: "provisional",
    dataNote: "Confirm all-day access before presenting these hours as official.",
  },
  {
    id: "aq-3169",
    name: "Mackenzie Café",
    shortName: "AQ Café",
    buildingCode: "AQ",
    building: "Academic Quadrangle",
    floor: 3,
    roomNumber: "3169",
    latitude: 49.27823,
    longitude: -122.9192,
    areaM2: 130.1,
    capacity: 70,
    hours: "8:30am–2:30pm",
    outlets: true,
    verification: "provisional",
    dataNote: "Workbook room and hours are provisional; verify against current SFU listings.",
  },
  {
    id: "asb-9702",
    name: "ASB Public Lounge 9702",
    shortName: "ASB 9702",
    buildingCode: "ASB",
    building: "Applied Sciences Building",
    floor: 9,
    roomNumber: "9702",
    latitude: 49.27802,
    longitude: -122.91502,
    areaM2: 27.9,
    capacity: 15,
    hours: "All day",
    outlets: true,
    verification: "provisional",
    dataNote: "Floor and all-day access were inferred from the workbook and need verification.",
  },
  {
    id: "asb-9703",
    name: "ASB Public Lounge 9703",
    shortName: "ASB 9703",
    buildingCode: "ASB",
    building: "Applied Sciences Building",
    floor: 9,
    roomNumber: "9703",
    latitude: 49.27816,
    longitude: -122.91478,
    areaM2: 27.9,
    capacity: 15,
    hours: "All day",
    outlets: true,
    verification: "provisional",
    dataNote: "Capacity was copied from the adjacent room; verify capacity, floor, and access.",
  },
  {
    id: "mbc-2270",
    name: "Black Student Centre Lounge",
    shortName: "MBC 2270",
    buildingCode: "MBC",
    building: "Maggie Benston Centre",
    floor: 2,
    roomNumber: "2270",
    latitude: 49.27915,
    longitude: -122.92145,
    areaM2: 126.3,
    capacity: 68,
    hours: "All day",
    outlets: true,
    verification: "provisional",
    dataNote: "Confirm all-day access before presenting these hours as official.",
  },
];

export const STUDY_SPOTS_SOURCE = {
  name: "SFU_Burnaby_Study_Spots_Updated.xlsx",
  importedRows: ROOMS.length,
  note: "Capacities, hours, estimated areas, and access details are prototype data and may require verification.",
} as const;

const ROOM_ID_ALIASES: Record<string, string> = {
  "aq-3000": "aq-303",
};

export function canonicalRoomId(roomId: string): string {
  return ROOM_ID_ALIASES[roomId] ?? roomId;
}

export function getRoom(roomId: string): Room | undefined {
  const canonicalId = canonicalRoomId(roomId);
  return ROOMS.find((room) => room.id === canonicalId);
}
